language: rust
os:
  - linux
  - osx
rust:
  - 1.31.0
  - stable
  - beta
  - nightly

sudo: false
env:
  global:
    - RUST_BACKTRACE=1

branches:
  except:
    - /test.*/

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
        ./scripts/verify-commit-messages.sh "$TRAVIS_COMMIT_RANGE" || exit 1;
    fi

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc

matrix:
  allow_failures:
    - rust: beta
    - rust: nightly
  include:
    - os: linux
      rust: stable
      name: clippy
      install:
        - rustup component add clippy
      script:
        - cargo clippy --verbose --all --tests

    - os: linux
      rust: stable
      sudo: required
      name: coverage
      addons: # needed for `cargo install cargo-travis`
        apt:
          packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
            - cmake
          sources:
            - kalakris-cmake
      cache:
        directories:
          - /home/travis/.cargo
          - /home/travis/build/tox-rs/tox/target/kcov-master
      before_cache:
        - rm -rf /home/travis/.cargo/registry
      install:
        - cargo install cargo-update --debug || echo "cargo-update has been already installed"
        - cargo install-update -i cargo-travis
      script:
        - mkdir -p target # fix for cargo-coveralls
        - cargo coveralls
