[package]
name = "tox"
version = "0.0.4"
authors = [
  "Zetok Zalbavar <zetok@openmailbox.org>",
  "Roman Proskuryakov <humbug@deeptown.org>",
  "Namsoo CHO <nscho66@gmail.com>",
  "Evgeny Kurnevsky <kurnevsky@gmail.com>",
]
readme = "README.md"
description = '''
Implementation of toxcore in pure Rust -
P2P, distributed, encrypted, easy
to use DHT-based network.
'''
documentation = "https://docs.rs/tox/"
repository = "https://github.com/tox-rs/tox/"
keywords = ["p2p", "instant-messaging", "tox", "toxcore", "networking"]
categories = ["multimedia"]
license = "GPL-3.0+"

[badges]
travis-ci = { repository = "tox-rs/tox" }
appveyor = { repository = "kpp/tox", id = "y3y2hi6552qgmfr0" }
coveralls = { repository = "tox-rs/tox" }
# Available options are `actively-developed`, `passively-maintained`,
# `as-is`, `none`, `experimental`, `looking-for-maintainer`, `deprecated`.
maintenance = { status = "actively-developed" }

[dependencies]
clippy = { version = "<= 0.1.0", optional = true }
bytes = "0.4"
byteorder = "1"
futures = "0.1"
log = "0.4"
sodiumoxide = "0.0.16"
tokio = "0.1"
tokio-io = "0.1"
nom = "3.2"
cookie-factory = "0.2.3"
get_if_addrs = "0.5.1"
parking_lot = "0.5"

[dev-dependencies]
env_logger = "0.5"
quickcheck = "0.6"
rand = "0.4"
rustc-serialize = "0.3"
tokio-timer = "0.2"
