[package]
name = "tox"
version = "0.0.1"
authors = ["Zetok Zalbavar <zetok@openmailbox.org>"]


[dependencies]
clippy = { version = "*", optional = true }
byteorder = "1"
futures = "0.1"
log = "0.3"
num-traits = "0.1"
sodiumoxide = "0.0.15"
tokio-core = "0.1"
tokio-proto = "0.1"

[dev-dependencies]
quickcheck = "0.4"
rand = "0.3"
regex = "0.2"
rustc-serialize = "0.3"
