[package]
name = "tox"
version = "0.0.1"
authors = ["Zetok Zalbavar <zetok@openmailbox.org>"]


[dependencies]
clippy = { version = "<= 0.1.0", optional = true }
bytes = "0.4"
byteorder = "1"
futures = "0.1"
log = "0.4"
sodiumoxide = "0.0.16"
tokio-core = "0.1"
tokio-proto = "0.1"
tokio-io = "0.1"
nom = "3.2"
cookie-factory = "0.2.2"

[dev-dependencies]
env_logger = "0.4"
quickcheck = "0.4"
rand = "0.3"
rustc-serialize = "0.3"
tokio-timer = "0.1"
