[package]
name = "tox"
version = "0.0.1"
authors = ["Zetok Zalbavar <zetok@openmailbox.org>"]


[dependencies]
clippy = { version = "*", optional = true }
log = "0.3"
num-traits = "0.1"
sodiumoxide = "0.0.15"
mio = "0.6"
byteorder = "1"

[dev-dependencies]
quickcheck = "0.4"
rand = "0.3"
regex = "0.2"
rustc-serialize = "0.3"
